### ISSUE TITLE
dataInfo and totalRecordCount

### ISSUE THREAD

**Issue by darnel** [msyk/FMDataAPI#35]
I would like to know total count of records to implement pagination. I discover there is such attribute in dataInfo by examining your source code. Unfortunately "my" response doesn't contain dataInfo key. Is there any way to enable it e.g. in request?
Thanks.

**Comment by mbcbus** [comment]
Check out the `getFoundCount` and `getReturnCount` class methods in the sample file here:
https://github.com/msyk/FMDataAPI/blob/master/samples/FMDataAPI_Sample.php

**Comment by darnel** [comment]
All three methods `getTotalCount()`, `getReturnedCount()` and `getFoundCount()` return `null`, because there is no `dataInfo` key in my HTTP response ([FMDataAPI.php:2112](https://github.com/msyk/FMDataAPI/blob/master/FMDataAPI.php#L2112)).
Is there way to convince FileMaker to return this metadata? Or other way to get number of available records?

I'm not admin of that database, so I can hardly make changes on its side.

Thanks for advices.

**Comment by mbcbus** [comment]
What version of the data API are you using, 17 or 18?

If you look under releases, the last two releases of this package are for FM18.
https://github.com/msyk/FMDataAPI/releases

Maybe you're using v17 which can't return that data? If that's the case, updating to 18 is the only way since you can't control what filemaker returns from their API.

**Comment by darnel** [comment]
You are right, it's API 17, thanks for clarification.
